version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
services:
  toposoid-feature-vectorizer:
    image: toposoid-feature-vectorizer:0.5-SNAPSHOT
    tty: true
    environment:
      - COMMON_NLP_JP_WEB_HOST=172.30.0.7
      - COMMON_NLP_EN_WEB_HOST=172.30.0.6
      - TOPOSOID_VALD_ACCESSOR_HOST=172.30.0.5
    networks:
      app_net:
        ipv4_address: 172.30.0.3
  toposoid-common-nlp-japanese-web:
    image: toposoid/toposoid-common-nlp-japanese-web:0.5-SNAPSHOT-workflow
    environment:
      - PRIVATE_IP_ADDRESS=192.168.33.10
      - SYNONYM_NOUN_SIMILARITY_THRESHHOLD_JP=0.52
      - SYNONYM_VERB_SIMILARITY_THRESHHOLD_JP=0.52
      - WORD2VEC_SIMILARITY_THRESHHOLD_JP=0.68
      - CHIVE_MODEL_VERSION=chive-1.2-mc90.kv
      - TOPOSOID_SENTENCEBERT_MODEL_JP=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - PLAY_HTTP_PORT=9006
    networks:
      app_net:
        ipv4_address: 172.30.0.7
    ports:
      - 9006:9006
  toposoid-common-nlp-english-web:
    image: toposoid/toposoid-common-nlp-english-web:0.5-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=192.168.33.10
      - SYNONYM_NOUN_SIMILARITY_THRESHHOLD_EN=0.52
      - SYNONYM_VERB_SIMILARITY_THRESHHOLD_EN=0.52
      - WORD2VEC_SIMILARITY_THRESHHOLD_EN=0.78
      - TOPOSOID_SENTENCEBERT_MODEL_EN=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - PLAY_HTTP_PORT=9008
    networks:
      app_net:
        ipv4_address: 172.30.0.6
    ports:
      - 9008:9008
  data-accessor-vald-web:
    image: toposoid/data-accessor-vald-web:0.5-SNAPSHOT
    environment:
      - TOPOSOID_VALD_HOST=172.30.0.2
      - TOPOSOID_VALD_PORT=8081
      - TOPOSOID_VALD_DISTANCE_THRESHHOLD=0.2 #For Multilingual Model 0.03
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    ports:
      - 9010:9010
  vald:
    image: vdaas/vald-agent-ngt:v1.7.6
    user: 1000:1000
    volumes:
      - ./vald-config:/etc/server
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 8081:8081
