FROM toposoid/toposoid-scala-lib-base:0.5-SNAPSHOT

WORKDIR /app
ARG TARGET_BRANCH
ENV DEPLOYMENT=local
ENV _JAVA_OPTIONS="-Xms512m -Xmx1g"

RUN apt-get update \
&& apt-get -y install git \
&& git clone https://github.com/toposoid/toposoid-feature-vectorizer.git \
&& cd toposoid-feature-vectorizer \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH}
