name: Unit Test
on:
  push:
    branches:
      - main
      - feature
  workflow_dispatch:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-feature-vectorizer
  PJ_BRANCH: feature
  PJ_VERSION: 0.4-SNAPSHOT
jobs:
  unit-test_toposoid-feature-vectorizer:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v2
        with:
            repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
      - name: Execute tests
        run: |
          cd ${GITHUB_WORKSPACE} && cd ../
          cd ./${{ env.PJ_REPO }}
          docker build --build-arg TARGET_BRANCH=${{ env.PJ_BRANCH }} --tag ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }} -f Dockerfile-workflow .
          docker-compose -f docker-compose-workflow.yml up -d
          docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt headerCheck"
          docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt test:headerCheck"
          docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt compile"
          docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt test"
      - name: Clone toposoid-scala-lib
        uses: actions/checkout@v2
        with:
          repository: ${{ env.PJ_ACTOR }}/toposoid-scala-lib
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: toposoid/toposoid-scala-lib:${{ env.PJ_VERSION }}
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: toposoid/toposoid-scala-lib:${{ env.PJ_VERSION }}
          build-args: |
            TARGET_BRANCH=${{ env.PJ_BRANCH }}
